spring:
  application:
    name: User-Service
  datasource:
    url: jdbc:mysql://mysql:3306/mydatabase
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
grpc:
  server:
    port: 9090